palette = "catppuccin_frappe"

format = """
$username\
$hostname\
$directory\
$git_state\
$git_status\
$line_break\
$character"""


[directory]
truncation_length = 2
# Catppuccin 'lavender'
style = "bold sapphire"
read_only = " 󰌾"

[character]
success_symbol = "[ ](mauve)"
error_symbol = "[ ](maroon)"
vimcmd_symbol = "[ ](mauve)"


[git_branch]
format = "[$branch]($style)"
style = "teal"

[git_status]
format = "[[($conflicted$untracked$modified)](peach) ($ahead_behind$stashed)]($style)"
style = "cyan"
ahead = '⇡'
behind = '⇣' 
conflicted = " "
# untracked = " "
modified = "*"
# # staged = "​"
# # renamed = "​"
# # deleted = "​"
 stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"


[python]
symbol = " "
format = "[$virtualenv]($style) "
style = "bright-black"


[aws]
symbol = "  "

[conda]
symbol = " "

[docker_context]
symbol = " "

[golang]
symbol = " "

[hostname]
ssh_symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[nodejs]
symbol = " "

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Linux = " "
Mabox = " "
Macos = " "
Raspbian = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[rust]
symbol = " "

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"
